### ISSUE TITLE
Support namespace packages

### ISSUE THREAD

**Issue by ekilmer** [trailofbits/cookiecutter-python#6]
Sometimes, it is preferred to use [namespace packaging](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/), and this template should support that.

Correct me if I'm wrong, but it looks like we should probably follow the [native namespace packages](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages) layout.

If we want to continue using `flit` with namespace packages, we will need to bump the version constraints to `>=3.5,<4` (https://github.com/pypa/flit/pull/468)

**Comment by woodruffw** [comment]
> Sometimes, it is preferred to use [namespace packaging](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/), and this template should support that.

Sounds reasonable to me 🙂 

> Correct me if I'm wrong, but it looks like we should probably follow the [native namespace packages](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages) layout.

Yep, I believe that's currently the most idiomatic approach.

**Comment by woodruffw** [comment]
> If we want to continue using `flit` with namespace packages, we will need to bump the version constraints to `>=3.5,<4` ([pypa/flit#468](https://github.com/pypa/flit/pull/468))

SGTM. I'd also be okay with moving to `hatch` or any other build backend; whatever's easiest.

**Comment by ekilmer** [comment]
Btw. I have a draft PR to resolve this #8. If you have any comments, I'm happy to hear/fix.

It's a draft because I still need to do a self-review but wanted to put it out there.
